"""add profile_embedding

Revision ID: 1e52360bbbc4
Revises: d1a00fae5bcc
Create Date: 2026-04-25 17:11:11.519449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1e52360bbbc4'
down_revision: Union[str, None] = 'd1a00fae5bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_embedding')
    # ### end Alembic commands ###

