"""phase 7 changes

Revision ID: 27b0092c6c7c
Revises: 9ef3d417948f
Create Date: 2026-04-12 13:57:57.580569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b0092c6c7c'
down_revision: Union[str, None] = '9ef3d417948f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

