"""job_extra_fields

Revision ID: 2a9a321542b8
Revises: 3ac2b6ea3a0e
Create Date: 2026-04-13 02:40:12.480840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9a321542b8'
down_revision: Union[str, None] = '3ac2b6ea3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('apply_link', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('schedule_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('posted_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'posted_at')
    op.drop_column('jobs', 'schedule_type')
    op.drop_column('jobs', 'apply_link')
    op.drop_column('jobs', 'source')
    # ### end Alembic commands ###

