"""profile_experience_roles

Revision ID: 30957d9fa627
Revises: a704f046db06
Create Date: 2026-04-13 03:36:03.307666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30957d9fa627'
down_revision: Union[str, None] = 'a704f046db06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('preferred_job_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'preferred_job_roles')
    op.drop_column('profiles', 'experience')
    # ### end Alembic commands ###

