"""ingestion_preferences

Revision ID: 3ac2b6ea3a0e
Revises: 6f353aea6337
Create Date: 2026-04-13 02:23:00.446439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac2b6ea3a0e'
down_revision: Union[str, None] = '6f353aea6337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_pipeline_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_refresh_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_ingestion_preferences_id'), 'ingestion_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_preferences_id'), table_name='ingestion_preferences')
    op.drop_table('ingestion_preferences')
    # ### end Alembic commands ###

