"""Add description_embedding vector column to jobs table

Revision ID: 6a1795c87d6e
Revises: bf7ae36526d3
Create Date: 2025-10-31 16:11:44.976342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6a1795c87d6e'
down_revision: Union[str, None] = 'bf7ae36526d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description_embedding')
    # ### end Alembic commands ###

