"""Post MVP additions

Revision ID: 9ef3d417948f
Revises: 44773afaab77
Create Date: 2026-04-12 13:46:36.996122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef3d417948f'
down_revision: Union[str, None] = '44773afaab77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_alert_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_preference', sa.String(), nullable=True),
    sa.Column('role_keywords', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_job_alert_preferences_id'), 'job_alert_preferences', ['id'], unique=False)
    op.add_column('chat_messages', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_job_alert_preferences_id'), table_name='job_alert_preferences')
    op.drop_table('job_alert_preferences')
    # ### end Alembic commands ###

