"""apply_options_json

Revision ID: a704f046db06
Revises: 2a9a321542b8
Create Date: 2026-04-13 02:47:35.469186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a704f046db06'
down_revision: Union[str, None] = '2a9a321542b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('apply_options', sa.JSON(), nullable=True))
    op.drop_column('jobs', 'apply_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('apply_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'apply_options')
    # ### end Alembic commands ###

